# Generated by Django 3.2.8 on 2021-10-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    def create_roles(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        role = apps.get_model('account', 'Role')
        role.objects.create(name='застройщик')
        role.objects.create(name='клиент')
        role.objects.create(name='агент')
        role.objects.create(name='нотариус')
    dependencies = [
        ('account', '0003_auto_20211019_1159')
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
