# Generated by Django 3.2.8 on 2021-10-19 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211019_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
