# Generated by Django 3.2.8 on 2021-10-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_client_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.CharField(choices=[('мне', 'мне'), ('мне и агенту', 'мне и агенту'), ('агенту', 'агенту'), ('отключить', 'отключить')], default='мне', max_length=50),
        ),
    ]
