# Generated by Django 3.2.8 on 2021-11-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userfilter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='account.user'),
        ),
    ]
