# Generated by Django 3.2.8 on 2021-10-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('district', models.CharField(max_length=50, verbose_name='Район')),
                ('microdistrict', models.CharField(max_length=50, verbose_name='Микрорайон')),
                ('price_for_meter', models.PositiveIntegerField(verbose_name='Цена за 1 м2')),
                ('areas', models.CharField(max_length=20, verbose_name='Площади')),
                ('frame_quantity', models.PositiveIntegerField(verbose_name='Кол-во корпусов')),
                ('infrastructure', models.TextField(verbose_name='Инфраструктура ЖК')),
                ('advantages', models.ManyToManyField(to='building.Advantage')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
