# Generated by Django 3.2.8 on 2021-10-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='infrastructure',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='house_class',
            field=models.CharField(choices=[('элитный', 'элитный'), ('новострой', 'новострой'), ('хрущевка', 'хрущевка')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='house_type',
            field=models.CharField(choices=[('многоквартирный', 'многоквартирный'), ('частный', 'частный')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='status',
            field=models.CharField(choices=[('квартиры', 'квартиры'), ('дома', 'дома')], max_length=20, null=True),
        ),
    ]
