# Generated by Django 3.2.8 on 2021-10-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_residentialcomplex_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('foundation_document', models.CharField(choices=[('собственность', 'собственность'), ('дар', 'дар')], max_length=100)),
                ('appointment', models.CharField(choices=[('апартаменты', 'апартаменты'), ('квартира', 'квартира'), ('частный дом', 'частный дом')], max_length=100, null=True)),
                ('room_quantity', models.PositiveIntegerField()),
                ('layout', models.CharField(choices=[('студия', 'студия'), ('изолированные коматы', 'изолированные комнаты'), ('смежные комнаты', 'смежные комнаты')], max_length=100)),
                ('living_condition', models.CharField(choices=[('новая', 'новая'), ('требует ремонта', 'требует ремонта'), ('аварийное', 'аварийное')], max_length=100)),
                ('area', models.FloatField()),
                ('kitchen_area', models.FloatField()),
                ('has_balcony', models.BooleanField()),
                ('heating_type', models.CharField(choices=[('центральное', 'центральное'), ('электрическое', 'электрическое'), ('водяное', 'водяное')], max_length=100)),
                ('sewerage_type', models.CharField(choices=[('центральная', 'центральная'), ('внутренняя', 'внутренняя'), ('внешняя', 'внешняя')], max_length=30, null=True)),
                ('calculation_options', models.CharField(max_length=100)),
                ('agent_commission', models.PositiveSmallIntegerField()),
                ('communication_method', models.CharField(choices=[('звонок', 'звонок'), ('сообщение', 'сообщение'), ('звонок и сообщение', 'звонок и сообщение')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('is_draft', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='appointment',
            field=models.CharField(max_length=30, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='calculation_options',
            field=models.CharField(max_length=30, null=True, verbose_name='Варианты расчета'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='ceiling_height',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='contract_amount',
            field=models.CharField(max_length=30, null=True, verbose_name='Неполная'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='distance_to_sea',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='heating_type',
            field=models.CharField(choices=[('центральное', 'центральное'), ('электрическое', 'электрическое'), ('водяное', 'водяное')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='house_territory',
            field=models.CharField(choices=[('закрытая', 'закрытая'), ('охраняемая', 'охраняемая'), ('закрытая охраняемая', 'закрытая охраняемая')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='is_gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='registration',
            field=models.CharField(max_length=30, null=True, verbose_name='Оформление'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='sewerage_type',
            field=models.CharField(choices=[('центральная', 'центральная'), ('внутренняя', 'внутренняя'), ('внешняя', 'внешняя')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='technology_of_building',
            field=models.CharField(choices=[('монолитный с каркассом', 'монолитный с каркассом'), ('керамические блоки', 'керамические блоки')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='water_supply_type',
            field=models.CharField(choices=[('центральное', 'центральное'), ('самотечное', 'самотечное'), ('комбинированное', 'комбинированное')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=7, null=True)),
                ('is_big', models.BooleanField(default=False)),
                ('to_high', models.BooleanField(default=False)),
                ('is_turbo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('finished', models.DateField()),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='building.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='building.residentialcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='house_documents')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='building.residentialcomplex')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='building.residentialcomplex'),
        ),
    ]
