# Generated by Django 3.2.8 on 2021-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_residentialcomplex_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='areas',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='max_area',
            field=models.FloatField(default=0.0, verbose_name='максимальная площадь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='min_area',
            field=models.FloatField(default=0.0, verbose_name='минимальная площадь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='advantages',
            field=models.ManyToManyField(null=True, to='building.Advantage'),
        ),
    ]
