# Generated by Django 3.2.8 on 2021-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_auto_20211025_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='level_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='riser_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='section_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
