# Generated by Django 3.2.8 on 2021-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_auto_20211025_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='building.Advantage'),
        ),
    ]
