# Generated by Django 3.2.8 on 2021-10-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_auto_20211026_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='building.announcement')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
