# Generated by Django 3.2.8 on 2021-10-27 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0010_auto_20211027_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='in_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
