# Generated by Django 3.2.8 on 2021-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_announcement_in_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
