# Generated by Django 3.2.8 on 2021-10-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_auto_20211027_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='post',
            new_name='announcement',
        ),
    ]
