# Generated by Django 3.2.8 on 2021-11-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_auto_20211029_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='building.announcement')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='building.residentialcomplex')),
            ],
        ),
    ]
