# Generated by Django 3.2.8 on 2021-11-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0016_requesttochest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='complex',
            new_name='residential_complex',
        ),
    ]
