# Generated by Django 3.2.8 on 2021-11-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0017_rename_complex_announcement_residential_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='frame',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='announcement',
            name='levele',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='announcement',
            name='section',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='advantages',
            field=models.ManyToManyField(blank=True, to='building.Advantage'),
        ),
    ]
