# Generated by Django 3.2.8 on 2021-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0018_auto_20211102_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='levele',
            new_name='level',
        ),
    ]
