# Generated by Django 3.2.8 on 2021-11-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0020_auto_20211102_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='complex',
            new_name='residential_complex',
        ),
    ]
