# Generated by Django 3.2.8 on 2021-11-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0021_rename_complex_news_residential_complex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='house',
            new_name='residential_complex',
        ),
    ]
