# Generated by Django 3.2.8 on 2021-11-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0022_rename_house_document_residential_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='finished',
            field=models.DateField(null=True),
        ),
    ]
