# Generated by Django 3.2.8 on 2021-11-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0023_alter_promotion_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='finished',
            field=models.DateField(),
        ),
    ]
